language: objective-c
os: osx
osx_image: xcode9.4
sudo: required
git:
  depth: 1
branches:
  only:
  - master

env:
  global:
  - BUILD_VERSION="0.0.2"
  - PYTHON_VERSION=3.6.9
  - PYENV_ROOT=~/.pyenv
  - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

before_install:
- brew upgrade pyenv || brew install pyenv
- PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install $PYTHON_VERSION
- pyenv global $PYTHON_VERSION
- python3 -m venv venv
- source venv/bin/activate

install:
- wget https://github.com/namuan/task-rider/archive/${BUILD_VERSION}.tar.gz -O ./taskrider.tar.gz
- tar -xvf ./taskrider.tar.gz
- mv task-rider-${BUILD_VERSION}/* .
- rm -rf taskrider.tar.gz task-rider-${BUILD_VERSION}
- python3 -m pip install -r requirements/base.txt

script:
- make package
# - ./import-cert.sh
# - ./mac-codesign.sh
- cd dist && zip "${TRAVIS_BUILD_DIR}"/taskrider-macos-${BUILD_VERSION}.zip -r taskrider.app && cd ..
- echo "Done!"

notifications:
  email: false

before_deploy:
- git config --local user.name "namuan"
- git remote set-url origin https://namuan:${GITHUB_TOKEN}@github.com/namuan/task-rider-releases.git
- git push origin :refs/tags/${BUILD_VERSION}
- git tag -f -am v${BUILD_VERSION} ${BUILD_VERSION}

deploy:
  provider: releases
  api-key: "${GITHUB_TOKEN}"
  file: "${TRAVIS_BUILD_DIR}/taskrider-macos-${BUILD_VERSION}.zip"
  overwrite: true
  skip_cleanup: true
  on:
    repo: namuan/task-rider-releases